[C++23] opus_fuzzer: Add missing C++23 headers
C++23 removed transitive includes so you need to add C++23 headers
directly to use its classes and functions. opus_enc_fuzzer needs
array for size and cstdlib for malloc. The files in the fuzzer are not
in upstream opus folder.

Errors:
external/libopus/fuzzer/opus_enc_fuzzer.cpp:95:46: error: use of
undeclared identifier 'malloc'; did you mean 'tzalloc'?
   95 |     unsigned char* mapping = (unsigned
char*)malloc(sizeof(unsigned char) * channels);
external/libopus/fuzzer/opus_enc_fuzzer.cpp:33:37: error: use of
undeclared identifier 'size'
   33 | constexpr size_t kSampleRatesSize = size(kSampleRates);
external/libopus/fuzzer/opus_enc_fuzzer.cpp:37:34: error: use of
undeclared identifier 'size'
   37 | constexpr size_t kChannelsSize = size(kChannels);
external/libopus/fuzzer/opus_enc_fuzzer.cpp:42:38: error: use of
undeclared identifier 'size'
   42 | constexpr size_t kApplicationsSize = size(kApplications);

Flag: EXEMPT PURE_REFACTOR
Bug: 429048222
Test: m opus_enc_fuzzer opus_multistream_enc_fuzzer
Change-Id: Ibbcf7a8db32e798363a9b834f57e13e6bbe21ef8